### ISSUE TITLE
Incorrect validation of callsign when that callsign is the destination field of an M17 packet. 

### ISSUE THREAD

**Issue by wgaylord** [n7tae/urfd#6]
Others were having an issue with urfd flagging M17 voice packets as invalid. After someone pointed out something that worked by changing the name of the reflector in Droidstar's host files I found the issue.

When someone using M17 talks there voice packets make its way into urfd which eventually calls 
[` bool CM17Protocol::IsValidDvPacket(const CBuffer &Buffer, std::unique_ptr<CDvHeaderPacket> &header, std::unique_ptr<CDvFramePacket> &frame)` ]( https://github.com/n7tae/urfd/blob/main/reflector/M17Protocol.cpp#L358-L383) on them. 

The area of issue is specifically when it calls header->IsValid() on line 378.
This calls[ `bool CDvHeaderPacket::IsValid(void) const`](https://github.com/n7tae/urfd/blob/4e2710c9132a170c186f72971b5ca376711bf367/reflector/DVHeaderPacket.cpp#L179-L192) which calls the isValid() function on each of the Callsigns that urfd uses as the header. 

Which are filled out at  https://github.com/n7tae/urfd/blob/4e2710c9132a170c186f72971b5ca376711bf367/reflector/DVHeaderPacket.cpp#L143-L151 where the M17 Dest Callsign is copied into m_csRPT1 and m_csRPT2. This dest Callsign normally takes the form of "M17-" then 3 more characters then a space and the target module on the reflector.

The isValid() function [ `bool CCallsign::IsValid(void) const`](https://github.com/n7tae/urfd/blob/4e2710c9132a170c186f72971b5ca376711bf367/reflector/Callsign.cpp#L91-L130) does not accept a callsign having a dash in it as a valid callsign which makes the Callsign invalid which makes the header invalid then finally the whole packet invalid. 

I am not sure how to fix this since the place where the validation happens has no knowledge of where the packet came from so can not specially handle M17 packets and also allowing dashes in callsigns may introduce other bugs down the road.

**Comment by wgaylord** [comment]
From the M17 side, to be on the public (beta) reflector list they are named M17- then 3 characters.

**Comment by n7tae** [comment]
urfd reflectors have to use URF??? as their callsign, while mrefd reflectors have to use M17-??? as their callsign. urfd reflectors operate in a domain where '-' is not a valid callsign character.

I still don't understand why you think this is an issue with urfd. I'm not sure what you would have me do to fix it.

**Comment by dbehnke** [comment]
Right now there is going to be a mix of M17-XXXX from the mrefd world and then what will need to make urefd happy.

What are your thoughts of having something convert the destination M17-XXX into the UREFd reflector name of currently running server before its run through the isVaild routine?   I think we are going to have a mixed world of people moving from mrefd and urefd.  and the reflector list has all M17-xxxxx names right now.   And keeping the M17-xxxx might be needed for the short term until this can be smoothed out.   Or if anyone else has a better idea.. just thinking off top of my head.  happy to chat about this if this is not making sense.

**Comment by wgaylord** [comment]
Also i would like to add that unless the M17 reflector list is updated to allow for reflector to start with something other them M17- urfd reflector can't actually exist on that list. And nothing says that list is for mrefd only reflectors. (As it stands my reflect runs on my own rust implementation.)

**Comment by n7tae** [comment]
All of the M17- reflectors listed on https://reflectors.m17.link/ref-list can potentially interlink with each other. An M17- reflector cannot interlink with a URF reflector. They use a totally different interlink packet structure.

We briefly discussed it, but I don't think Steve KC1AWV will be adding URF reflectors to the M17 ref-list and I agree with that. A new website listing URF reflectors would be cool, but I don't think the M17 Project should host it. For now at least, since URF is a superset of XLX, URF reflector owners can use the XLX reflector list as long as their chosen suffix is available.

I think it's important that M17 clients should distinguish between URF and M17- reflectors, so I would resist what this issue aims to do: To allow, for example, a client to use a URFXYZ reflector by setting a destination callsign of M17-XYZ. It is confusing for users, especially if there is already an operational mrefd reflector using M17-XYZ as its callsign.

You could argue that there is precedence for this idea because a D-Star client can link to URFXYZ using REFXYZ, DCSXYZ, or XRFXYZ, but there is a big difference, that D-Star client will be using CQCQCQ in its UR callsign when trasmitting to the URFXYZ reflector.

**Comment by dbehnke** [comment]
ok that makes sense to me and I agree. thanks for explaining the D-Star concern and incompatibility with mrefd.   I guess many of us (including myself) were thinking this was a drop in replacement for mrefd and that the clients would be happy..  ad8dp has suggested a custom entry in hostsfile for droidstar.. that will work for me.

**Comment by wgaylord** [comment]
Okay. Then should urfd be validating that the DST callsign is of form URF???, right now it will happily accept alot of different strings as the Dst callsign. Not matter how they start.

**Comment by n7tae** [comment]
Yes, it probably should, but there isn't a lot of that type of checking on any protocol. If it becomes an issue, it can be added then.

And yes, that's correct. "mrefd" is just the name of the executable as set by the Makefile. Having said that, M17- is reflector that only accepts M17 clients. Just like REF, DCS and XRF are reflectors that only accept D-Star clients.

**Comment by wgaylord** [comment]
Well I will close this I guess. Since it sortof isn't an issue now that it was explained.

**Comment by Danny9589** [comment]
Does anyone have a fix for droidstar iPhone vocoders the old one stop working.
